## Numpy

**Importe a lib numpy**

In [1]:
import numpy as np

**Crie um lista de 10 itens, onde cada tenha um intervalo de 3 valores**

In [2]:
#Modo 1
lista = np.arange(0,31,3)
lista

#Modo 2
lista = np.arange(31,step=3)
lista

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30])

**pegue apenas os numeros entre a posição 3 e 8, e salve em lista2**

In [3]:
lista2 = lista[3:8]
lista2

array([ 9, 12, 15, 18, 21])

**Divida todos os numeros de lista2 por 3, salve em uma nova variavel**

In [4]:
lista3 = lista2 / 3
lista3

array([3., 4., 5., 6., 7.])

**Transforme estes numeros em no tipo inteiro, salve na mesma variavel**

In [5]:
lista4 = lista3.astype(int)
lista4

array([3, 4, 5, 6, 7])

**Crie um array aleatorio de 15 itens entre 0 e 100**

In [7]:
np.random.seed(100)

lista_random = np.random.randint(0,100,15)
lista_random

array([ 8, 24, 67, 87, 79, 48, 10, 94, 52, 98, 53, 66, 98, 14, 34])

**Qual o maior numero?**

In [10]:
lista_random.max()

98

**Qual o índice do maior número?**

In [11]:
lista_random.argmax()

9

**Verifique quais numeros são maior que 10**

In [12]:
lista_random > 10

array([False,  True,  True,  True,  True,  True, False,  True,  True,
        True,  True,  True,  True,  True,  True])

**salve em uma nova matriz apenas os maiores que 10**

In [13]:
lista_random[lista_random > 10]

array([24, 67, 87, 79, 48, 94, 52, 98, 53, 66, 98, 14, 34])

## Matriz

**Gere uma matriz 3,3, será nescessario criar uma lista e transformá-la em matriz**

In [15]:
lista = np.arange(3*3)
lista.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

**Gere uma matriz 3x3 aleatória com números entre 0 e 100**

In [21]:
np.random.seed(100)

lista = np.random.randint(0, 100, 9)
lista.reshape(3, 3)

array([[ 8, 24, 67],
       [87, 79, 48],
       [10, 94, 52]])

## Pandas

In [22]:
import pandas as pd

## Serie

**Crie uma serie com 10 numeros**

In [23]:
minha_lista = np.arange(10)
serie = pd.Series(minha_lista)
serie

0    0
1    1
2    2
3    3
4    4
5    5
6    6
7    7
8    8
9    9
dtype: int32

**Coloque um index nesta serie ['a','b','c','d','e','f','g','h','e','f']**

In [24]:
labels =  ['a','b','c','d','e','f','g','h','e','f'] 
serie.index = labels
serie

a    0
b    1
c    2
d    3
e    4
f    5
g    6
h    7
e    8
f    9
dtype: int32

**crie uma serie com 4 numeros sendo com mesmo valor**

In [25]:
lista = ['a','b','c','a']
serie = pd.Series(lista)
serie

0    a
1    b
2    c
3    a
dtype: object

**Conte quanto vezes cada numero aparece** 

In [26]:
serie.value_counts()

a    2
c    1
b    1
dtype: int64

**Faça uma nova lista com apenas o valor repetido**

In [27]:
#Modo 1
serie[serie == 'a']

0    a
3    a
dtype: object

In [28]:
#Modo 2
serie[serie.isin(['a'])]

0    a
3    a
dtype: object

## DataFrame 

**Leia o arquivo tips** 

In [29]:
tips = pd.read_csv('../datasets/tips.csv')
tips.head()

Unnamed: 0  total_bill   tip     sex smoker  day    time  size
0           0       16.99  1.01  Female     No  Sun  Dinner     2
1           1       10.34  1.66    Male     No  Sun  Dinner     3
2           2       21.01  3.50    Male     No  Sun  Dinner     3
3           3       23.68  3.31    Male     No  Sun  Dinner     2
4           4       24.59  3.61  Female     No  Sun  Dinner     4

**Qual o total de valores vendidos pelo restaurantes?**

In [31]:
tips['total_bill'].sum()

4827.77

**Qual o foi a gorjeta  total recebida pelos funcionarios do restaurantes?**

In [32]:
tips['tip'].sum()

731.5799999999999

**Veja a linha time**

In [33]:
tips['time'].head()

0    Dinner
1    Dinner
2    Dinner
3    Dinner
4    Dinner
Name: time, dtype: object

**Verifique os tipos unicos**

In [34]:
tips['time'].unique()

array(['Dinner', 'Lunch'], dtype=object)

**Existem um numero maior de vendas no almoço ou no jantar?**

In [35]:
tips['time'].value_counts()

Dinner    176
Lunch      68
Name: time, dtype: int64

**Agora imprima so os tipos Lunch salve em uma variavel lunch**

In [36]:
lunch = tips[tips['time'] == 'Lunch']
lunch.head()

Unnamed: 0  total_bill   tip   sex smoker   day   time  size
77          77       27.20  4.00  Male     No  Thur  Lunch     4
78          78       22.76  3.00  Male     No  Thur  Lunch     2
79          79       17.29  2.71  Male     No  Thur  Lunch     2
80          80       19.44  3.00  Male    Yes  Thur  Lunch     2
81          81       16.66  3.40  Male     No  Thur  Lunch     2

**Agora mostre os os que tiveram tips maior que 2**

In [37]:
lunch[lunch['tip'] > 2].head()

Unnamed: 0  total_bill   tip   sex smoker   day   time  size
77          77       27.20  4.00  Male     No  Thur  Lunch     4
78          78       22.76  3.00  Male     No  Thur  Lunch     2
79          79       17.29  2.71  Male     No  Thur  Lunch     2
80          80       19.44  3.00  Male    Yes  Thur  Lunch     2
81          81       16.66  3.40  Male     No  Thur  Lunch     2

**Descubra qual refeição gera mais lucro medio, para isto utilize de máscaras**

In [38]:
valorLunch = lunch[lunch['time'] =='Lunch']['total_bill'].mean()
print("Lunch:",valorLunch)

Lunch: 17.16867647058823


In [39]:
valorDinner = tips[tips['time'] =='Dinner']['total_bill'].mean()
print("Dinner:",valorDinner)

Dinner: 20.7971590909091
