# Aula 1: Introdução ao Numpy e Pandas

### Atalhos do jupyter notebook

- `ctrl + enter`: rodar a célula e permanecer nela
- `shift + enter`: rodar a célula e vai para a próxima
- `esc`: deseleciona a célula
- `enter`: seleciona a célula
- `a`: cria célula acima (above)
- `b`: cria célula abaixo (below)
- `x`: recortar célula
- `c`: copiar célula
- `v`: colar célula
- `z`: desfazer ação
- `m`: transformar célula em markdown

## Códigos

### Numpy

Numpy é uma biblioteca das principais bibliotecas do Python, devido a sua grande velocidade e eficiência ele é extremamente utilizada para computação científica e analise de dados. Esta fama se da principalmente a estrutura chamada [numpy array](https://docs.scipy.org/doc/numpy/reference/arrays.html), um forma eficiente de guardar e manipular matrizes, que serve como base para as tabelas que iremos utilizar.

Abaixo começaremos o codigo passado em aula:

In [3]:
import numpy as np

#### Criando listas

In [48]:
# criando listas numpy a partir de listas do python
lista = [1,2,3,4,5]
listaNumpy = np.array(lista)
print(listaNumpy)

[1 2 3 4 5]


In [49]:
#Criando array zeros nump
zeros = np.zeros(10)
zeros

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [50]:
#Criando array 1 
uns = np.ones(10)
uns

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [22]:
#Criando array de um numero qualquer
cincos = np.ones(10) * 5
cincos

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [23]:
#Criando array com sequencia
lista10 = np.arange(0,10)
lista10

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
#Criando lista Com saltos
listaD = np.arange(0,20,2)
listaD

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [25]:
#Array espaçado, os dois primeiros numeros são o intervalo, o terceiro e numero de valores 
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [26]:
#Criando array com valores aleatorios
aleatorio = np.random.rand(20)
aleatorio

array([0.86610619, 0.24127259, 0.7061093 , 0.12472191, 0.0551103 ,
       0.30603911, 0.33681716, 0.2488249 , 0.08111344, 0.7250505 ,
       0.67832453, 0.57370073, 0.81418697, 0.38404795, 0.08589182,
       0.95724993, 0.42486225, 0.74437799, 0.88086497, 0.19937592])

In [27]:
# aleatorio inteiro (10 itens de 0 a 100)
lista1 = np.random.randint(0,100,10)
lista1

array([ 7, 78, 28, 12, 55, 41, 67, 52, 42, 58])

#### Indexação

In [51]:
lista10[5]

5

In [52]:
#Partindo array
lista10[2:7]

array([2, 3, 4, 5, 6])

In [53]:
parte = lista10[3:8]
parte

array([3, 4, 5, 6, 7])

In [28]:
#Criando array com sequencia
lista40 = np.arange(10,50)
lista40

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### Operações simples

In [54]:
lista1 * 2

array([ 14.,  24.,  56.,  82.,  84., 104., 110., 116., 134., 156.])

In [55]:
lista1 + 1

array([ 8., 13., 29., 42., 43., 53., 56., 59., 68., 79.])

In [56]:
lista1 ** 2

array([  49.,  144.,  784., 1681., 1764., 2704., 3025., 3364., 4489.,
       6084.])

In [57]:
lista1 / 2

array([ 3.5,  6. , 14. , 20.5, 21. , 26. , 27.5, 29. , 33.5, 39. ])

#### Operações com várias listas

In [58]:
#soma
lista2 = np.random.randint(0,100,10)
lista1 + lista2

array([ 18.,  70.,  50., 114.,  95.,  82., 126., 139.,  71., 164.])

In [59]:
# divisão
lista1 / lista2

array([ 0.63636364,  0.20689655,  1.27272727,  0.56164384,  0.79245283,
        1.73333333,  0.77464789,  0.71604938, 16.75      ,  0.90697674])

In [60]:
#divisão mult
lista1 * lista2

array([  77.,  696.,  616., 2993., 2226., 1560., 3905., 4698.,  268.,
       6708.])

#### Métodos

In [61]:
#Funções sobre uma matriz
#maior valor
lista1.max()

78.0

In [62]:
#local do maior valor
lista1.argmax()

9

In [64]:
#maior valor
lista1.min()

7.0

In [65]:
#local do menor valor
lista1.argmin()

0

In [67]:
#soma de todos os items
lista1.sum()

440.0

In [68]:
#media
lista1.mean()

44.0

In [69]:
#desvio padrão
lista1.std()

21.743964679883014

In [70]:
#ordenar a lista
lista1.sort()
lista1

array([ 7., 12., 28., 41., 42., 52., 55., 58., 67., 78.])

In [72]:
#Trocando o tipo dos dados nas lista
lista1 = lista1.astype(int)
lista1

array([ 7, 12, 28, 41, 42, 52, 55, 58, 67, 78])

#### Matrix

In [73]:
listaD = np.arange(0,20,2)

In [76]:
#Criando matriz
matriz = listaD.reshape(5, 2)
matriz

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10],
       [12, 14],
       [16, 18]])

In [77]:
#mostra qual é o formato da matriz
matriz.shape

(5, 2)

In [78]:
#Criando matriz identidade
mIdentidade = np.eye(5)
mIdentidade

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [79]:
#indexação matriz
matriz[2:,1:]

array([[10],
       [14],
       [18]])

#### Máscaras

In [80]:
#Mascaras
aleatorio > 0.5

array([ True, False,  True, False, False, False, False, False, False,
        True,  True,  True,  True, False, False,  True, False,  True,
        True, False])

In [81]:
#Numeros pares
pares = lista10 % 2 == 0
pares

array([ True, False,  True, False,  True, False,  True, False,  True,
       False])

In [82]:
#Aplicando a mascara a mastriz
lista10[pares]

array([0, 2, 4, 6, 8])

In [83]:
#Aplicando a mascara maior que 2
lista10[lista10>2]

array([3, 4, 5, 6, 7, 8, 9])

### Pandas

#### Series

`Series` representam as colunas das tabelas, guardando seu conteúdo com numpy arrays, porem neste caso cada array tem um index, que permite acessar o conteúdo das series como um similar a um dicionário python. além disso essa classe conta com alguns métodos mais avançados que o numpy array.

In [84]:
import pandas as pd

In [85]:
#utilizando um lista simples
minha_lista = [10,20,30]
serie = pd.Series(minha_lista)
serie

0    10
1    20
2    30
dtype: int64

In [88]:
#Acessando dados como um lista
serie[1]

20

In [90]:
#indexação
serie[:2]

0    10
1    20
dtype: int64

In [91]:
#Series com index
labels = ['a','b','c','e']
lista4 = [10,20,30,40]
serieLabel = pd.Series(data=lista4,index=labels)
serieLabel

a    10
b    20
c    30
e    40
dtype: int64

In [92]:
#acessando index 'a' da serie
serieLabel['a']

10

In [93]:
#acessando index 'a' e 'b' da serie
serieLabel['a':'b']

a    10
b    20
dtype: int64

In [94]:
#Series com dicionarios
dicionario = {'a':10,'b':20,'c':30}
pd.Series(dicionario)

a    10
b    20
c    30
dtype: int64

In [95]:
#operações com series
dic1 = {"Brasil":10,"EUA":10,"Japão":10}
serie1 = pd.Series(dic1)
dic2 = {"Brasil":10,"Bolivia":10,"Japão":10}
serie2 = pd.Series(dic2)
serie1 + serie2

Bolivia     NaN
Brasil     20.0
EUA         NaN
Japão      20.0
dtype: float64

In [96]:
#unique
serie1 = pd.Series(['a','b','c','a','d','e','c','a','e','d'])
serie1.unique()

array(['a', 'b', 'c', 'd', 'e'], dtype=object)

In [97]:
#Contando valores
serie1.value_counts()

a    3
e    2
d    2
c    2
b    1
dtype: int64

In [98]:
#isin - Para filtar valores
mask = serie1.isin(['b', 'c'])
mask

serie1[mask]

1    b
2    c
6    c
dtype: object

#### Dataframe

E por ultimo temos a estrutura DataFrame, esta será nossa tabela, representada por um dicionário de series com o mesmo index.

In [99]:
np.random.seed(42) #Para o rand ficar igual

lista = np.random.randn(5,3)
lista

array([[ 0.49671415, -0.1382643 ,  0.64768854],
       [ 1.52302986, -0.23415337, -0.23413696],
       [ 1.57921282,  0.76743473, -0.46947439],
       [ 0.54256004, -0.46341769, -0.46572975],
       [ 0.24196227, -1.91328024, -1.72491783]])

In [100]:
index = ['a','b','c','d','e']
colunas = ['x','y','z']
dataFrame = pd.DataFrame(data = lista,index=index,columns=colunas)
dataFrame

x         y         z
a  0.496714 -0.138264  0.647689
b  1.523030 -0.234153 -0.234137
c  1.579213  0.767435 -0.469474
d  0.542560 -0.463418 -0.465730
e  0.241962 -1.913280 -1.724918

In [101]:
# acessando coluna 'x', retornando uma serie
dataFrame['x']

a    0.496714
b    1.523030
c    1.579213
d    0.542560
e    0.241962
Name: x, dtype: float64

In [102]:
# acessando colunas 'x' e 'y', retornando um dataframe
dataFrame[['x','y']]

x         y
a  0.496714 -0.138264
b  1.523030 -0.234153
c  1.579213  0.767435
d  0.542560 -0.463418
e  0.241962 -1.913280

In [104]:
#pegando ponto
dataFrame['x']['a']

0.4967141530112327

In [105]:
#Pegando linha
dataFrame.loc['a']

x    0.496714
y   -0.138264
z    0.647689
Name: a, dtype: float64

In [107]:
#Pegando linha por numero
dataFrame.iloc[2]

x    1.579213
y    0.767435
z   -0.469474
Name: c, dtype: float64

In [108]:
#pegando linha e colunuma
dataFrame.loc['a','x']

0.4967141530112327

In [109]:
dataFrame.loc[['a','b'],['x','y']]

x         y
a  0.496714 -0.138264
b  1.523030 -0.234153

In [110]:
#nova coluna 
dataFrame['novo'] = dataFrame['x'] + dataFrame['y']
dataFrame

x         y         z      novo
a  0.496714 -0.138264  0.647689  0.358450
b  1.523030 -0.234153 -0.234137  1.288876
c  1.579213  0.767435 -0.469474  2.346648
d  0.542560 -0.463418 -0.465730  0.079142
e  0.241962 -1.913280 -1.724918 -1.671318

In [111]:
#remove mas não salva
dataFrame.drop('novo',axis=1)

x         y         z
a  0.496714 -0.138264  0.647689
b  1.523030 -0.234153 -0.234137
c  1.579213  0.767435 -0.469474
d  0.542560 -0.463418 -0.465730
e  0.241962 -1.913280 -1.724918

In [112]:
dataFrame

x         y         z      novo
a  0.496714 -0.138264  0.647689  0.358450
b  1.523030 -0.234153 -0.234137  1.288876
c  1.579213  0.767435 -0.469474  2.346648
d  0.542560 -0.463418 -0.465730  0.079142
e  0.241962 -1.913280 -1.724918 -1.671318

In [113]:
#remove e salva
dataFrame.drop('novo',axis=1,inplace=True)
dataFrame

x         y         z
a  0.496714 -0.138264  0.647689
b  1.523030 -0.234153 -0.234137
c  1.579213  0.767435 -0.469474
d  0.542560 -0.463418 -0.465730
e  0.241962 -1.913280 -1.724918

In [114]:
#retirando colunas
dataFrame.drop('e',axis=0)

x         y         z
a  0.496714 -0.138264  0.647689
b  1.523030 -0.234153 -0.234137
c  1.579213  0.767435 -0.469474
d  0.542560 -0.463418 -0.465730

In [115]:
#Seleções através de condições
dataFrame>0

x      y      z
a  True  False   True
b  True  False  False
c  True   True  False
d  True  False  False
e  True  False  False

In [116]:
#utilizando condição como mascara para um novo dataFrame
dataFrame[dataFrame>0]

x         y         z
a  0.496714       NaN  0.647689
b  1.523030       NaN       NaN
c  1.579213  0.767435       NaN
d  0.542560       NaN       NaN
e  0.241962       NaN       NaN

In [117]:
#porem não salva
dataFrame

x         y         z
a  0.496714 -0.138264  0.647689
b  1.523030 -0.234153 -0.234137
c  1.579213  0.767435 -0.469474
d  0.542560 -0.463418 -0.465730
e  0.241962 -1.913280 -1.724918

In [118]:
#retira a linha do y que tem um item menor que 0
dataFrame[dataFrame['y']>0]

x         y         z
c  1.579213  0.767435 -0.469474

In [119]:
#Mesma operação de cima porem so retorna o linha z
dataFrame[dataFrame['y']>0]['z']

c   -0.469474
Name: z, dtype: float64

In [120]:
#resetando index
dataFrame.reset_index()

index         x         y         z
0     a  0.496714 -0.138264  0.647689
1     b  1.523030 -0.234153 -0.234137
2     c  1.579213  0.767435 -0.469474
3     d  0.542560 -0.463418 -0.465730
4     e  0.241962 -1.913280 -1.724918

In [121]:
dataFrame['nomes'] = ['SP','RJ','BH','SSA','NV']

In [122]:
#criando novo index
dataFrame.set_index('nomes',inplace=True)

dataFrame

x         y         z
nomes                              
SP     0.496714 -0.138264  0.647689
RJ     1.523030 -0.234153 -0.234137
BH     1.579213  0.767435 -0.469474
SSA    0.542560 -0.463418 -0.465730
NV     0.241962 -1.913280 -1.724918

**indices multiplos**

In [124]:
outside = ['G1','G1','G1','G2','G2','G2']
inside = [1,2,3,1,2,3]
hier_index = list(zip(outside,inside))
hier_index = pd.MultiIndex.from_tuples(hier_index)

hier_index

MultiIndex([('G1', 1),
            ('G1', 2),
            ('G1', 3),
            ('G2', 1),
            ('G2', 2),
            ('G2', 3)],
           )

In [125]:
matriz = np.random.randn(6,2)
matriz

array([[-0.56228753, -1.01283112],
       [ 0.31424733, -0.90802408],
       [-1.4123037 ,  1.46564877],
       [-0.2257763 ,  0.0675282 ],
       [-1.42474819, -0.54438272],
       [ 0.11092259, -1.15099358]])

In [126]:
df = pd.DataFrame(matriz,index=hier_index,columns=['A','B'])

df

A         B
G1 1 -0.562288 -1.012831
   2  0.314247 -0.908024
   3 -1.412304  1.465649
G2 1 -0.225776  0.067528
   2 -1.424748 -0.544383
   3  0.110923 -1.150994

In [127]:
df.loc['G1']

A         B
1 -0.562288 -1.012831
2  0.314247 -0.908024
3 -1.412304  1.465649

In [128]:
df.xs('G1')

A         B
1 -0.562288 -1.012831
2  0.314247 -0.908024
3 -1.412304  1.465649

##### Concats e merges

In [129]:
df1 = pd.DataFrame({'A':[1,2,3],'B':[4,5,6],'C':[7,8,9]},index=['w','x','y'])
df2 = pd.DataFrame({'B':[1,2,3],'C':[4,5,6],'D':[7,8,9]},index=['x','y','z'])

In [131]:
df1

A  B  C
w  1  4  7
x  2  5  8
y  3  6  9

In [132]:
df2

B  C  D
x  1  4  7
y  2  5  8
z  3  6  9

In [133]:
pd.concat([df1,df2])

C:\Users\milto\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  """Entry point for launching an IPython kernel.


A  B  C    D
w  1.0  4  7  NaN
x  2.0  5  8  NaN
y  3.0  6  9  NaN
x  NaN  1  4  7.0
y  NaN  2  5  8.0
z  NaN  3  6  9.0

In [134]:
pd.concat([df1,df2],join='inner')

B  C
w  4  7
x  5  8
y  6  9
x  1  4
y  2  5
z  3  6

In [135]:
pd.concat([df1,df2],axis=1)

C:\Users\milto\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  """Entry point for launching an IPython kernel.


A    B    C    B    C    D
w  1.0  4.0  7.0  NaN  NaN  NaN
x  2.0  5.0  8.0  1.0  4.0  7.0
y  3.0  6.0  9.0  2.0  5.0  8.0
z  NaN  NaN  NaN  3.0  6.0  9.0

In [136]:
pd.concat([df1, df2], axis=1, join='inner')

A  B  C  B  C  D
x  2  5  8  1  4  7
y  3  6  9  2  5  8

In [137]:
df3 = pd.DataFrame({'Paises':['Br','Pt','Bo'],'valor1':[1,2,3],"Valor2":[3,4,5]})
df4 = pd.DataFrame({'Paises':['Br','Pt','Bo'],'valor3':[1,2,3],"Valor4":[3,4,5]})

df3 

Paises  valor1  Valor2
0     Br       1       3
1     Pt       2       4
2     Bo       3       5

In [139]:
df4

Paises  valor3  Valor4
0     Br       1       3
1     Pt       2       4
2     Bo       3       5

In [138]:
pd.merge(df3, df4, on='Paises')

Paises  valor1  Valor2  valor3  Valor4
0     Br       1       3       1       3
1     Pt       2       4       2       4
2     Bo       3       5       3       5

#### Importando dados

In [41]:
df_imoveis_rj = pd.read_csv('../datasets/imoveis_rj.csv')
df_imoveis_rj.head()

condominio;quartos;suites;vagas;area;bairro;atualizacao;preco;distancia;pm2
0          350;1;0.0;1.0;21;1;1;340000;99.0;16190.48                         
1          800;1;0.0;1.0;64;1;0;770000;99.0;12031.25                         
2           674;1;0.0;1.0;61;1;1;600000;99.0;9836.07                         
3           700;1;1.0;1.0;70;1;0;700000;99.0;10000.0                         
4          440;1;0.0;1.0;44;1;2;515000;99.0;11704.55

##### Nan Values

In [140]:
#Drop nan
df = pd.DataFrame({'col1':[1,2,3,np.nan],
                   'col2':[np.nan,555,666,444],
                   'col3':['abc','def','ghi','xyz']})
df.head()

col1   col2 col3
0   1.0    NaN  abc
1   2.0  555.0  def
2   3.0  666.0  ghi
3   NaN  444.0  xyz

In [141]:
df.dropna()

col1   col2 col3
1   2.0  555.0  def
2   3.0  666.0  ghi

In [142]:
df.fillna('Preencher')

col1       col2 col3
0          1  Preencher  abc
1          2        555  def
2          3        666  ghi
3  Preencher        444  xyz

#### Titanic

In [143]:
df_titanic = pd.read_csv('../datasets/titanic.csv')

In [144]:
df_titanic.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [146]:
df_titanic['Age'].mean()

29.69911764705882

In [147]:
df_titanic['Age'].mean()

29.69911764705882

In [148]:
df_titanic['Age'].std()

14.526497332334044

In [149]:
df_titanic['Age'].mode()

0    24.0
dtype: float64

In [150]:
df_titanic['Age'].max()

80.0

In [154]:
df_titanic['Age'].min()

0.42

In [152]:
df_titanic['Age'].value_counts()

24.00    30
22.00    27
18.00    26
19.00    25
30.00    25
         ..
55.50     1
70.50     1
66.00     1
23.50     1
0.42      1
Name: Age, Length: 88, dtype: int64

In [155]:
df_titanic['Age'].describe()

count    714.000000
mean      29.699118
std       14.526497
min        0.420000
25%       20.125000
50%       28.000000
75%       38.000000
max       80.000000
Name: Age, dtype: float64

In [174]:
df_titanic.groupby('Embarked')['Survived'].agg(casos='count',
                                               media='mean')

casos     media
Embarked                 
C           168  0.553571
Q            77  0.389610
S           644  0.336957

In [145]:
df_titanic.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [175]:
df_titanic['Embarked'].value_counts()

S    644
C    168
Q     77
Name: Embarked, dtype: int64

In [185]:
df_titanic['Embarked'].mode()[0]

'S'

In [188]:
df_titanic['Embarked'].fillna(df_titanic['Embarked'].mode()[0]).value_counts()

S    646
C    168
Q     77
Name: Embarked, dtype: int64

In [189]:
df_titanic.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [192]:
df_titanic.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [195]:
drop_col = ['PassengerId', 'Name']
df_titanic.drop(drop_col, axis=1).duplicated()

0      False
1      False
2      False
3      False
4      False
       ...  
886    False
887    False
888    False
889    False
890    False
Length: 891, dtype: bool

In [196]:
mask = df_titanic.drop(drop_col, axis=1).duplicated()

In [203]:
df_titanic.loc[mask, ].head()

PassengerId  Survived  Pclass                            Name     Sex  \
201          202         0       3             Sage, Mr. Frederick    male   
324          325         0       3        Sage, Mr. George John Jr    male   
409          410         0       3              Lefebre, Miss. Ida  female   
413          414         0       2  Cunningham, Mr. Alfred Fleming    male   
466          467         0       2           Campbell, Mr. William    male   

     Age  SibSp  Parch    Ticket     Fare Cabin Embarked  
201  NaN      8      2  CA. 2343  69.5500   NaN        S  
324  NaN      8      2  CA. 2343  69.5500   NaN        S  
409  NaN      3      1      4133  25.4667   NaN        S  
413  NaN      0      0    239853   0.0000   NaN        S  
466  NaN      0      0    239853   0.0000   NaN        S